name: CI/CD Pipeline DEV

on:
  push:
    branches:
      - dev

env:
  AWS_ACCOUNT: "923672208632"
  AWS_REGION: "us-east-1"
  CLUSTER_NAME: "linuxtips-ecscluster"
  APP_NAME: "linuxtips-app"
  REPO_NAME: "linuxtips/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Go Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1

      - name: Run Go Lint
        run: golangci-lint run ./... -E errcheck
        working-directory: ./app

      - name: Run Go Test
        run: go test ./... -v
        working-directory: ./app

  ci-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7

      - name: Terraform Format Check
        run: terraform fmt -recursive -check
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init -backend-config="environment/${GITHUB_REF_NAME}/backend.tfvars"
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
